[{
  title: "post title",
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia voluptatibus perspiciatis, minima culpa modi vero labore aut dignissimos quas fugiat corporis ipsam eligendi hic a aliquid ducimus optio, veritatis dicta.",
  ingredients: ["ingredient1", "ingredient2", "ingredient3", "ingredient4"],
  method: ["method1", "method2", "method3", "method4"],
  featured: true,
  date: "date string here",
  author: "Yorick",
  tags: ["tag1", "tag2", "tag3"],
  difficulty: 3,
  cookTime: "1 Hour",
  prepTime: "20 minutes",
  servingSize: 4,
  numberOfComments: 0,
  numberOfFavorites: 2,
  typeOfPost: "Recipe"

}, {
  title: "post title 22222",
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia voluptatibus perspiciatis, minima culpa modi vero labore aut dignissimos quas fugiat corporis ipsam eligendi hic a aliquid ducimus optio, veritatis dicta.",
  ingredients: ["ingredient1", "ingredient2", "ingredient3", "ingredient4"],
  method: ["method1", "method2", "method3", "method4"],
  featured: true,
  date: "date string here",
  author: "Yorick",
  tags: ["tag1", "tag2", "tag3"],
  difficulty: 3,
  cookTime: "1 Hour",
  prepTime: "20 minutes",
  servingSize: 4,
  numberOfComments: 0,
  numberOfFavorites: 2,
  typeOfPost: "Recipe"

}, {
  title: "post title 33333",
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia voluptatibus perspiciatis, minima culpa modi vero labore aut dignissimos quas fugiat corporis ipsam eligendi hic a aliquid ducimus optio, veritatis dicta.",
  ingredients: ["ingredient1", "ingredient2", "ingredient3", "ingredient4"],
  method: ["method1", "method2", "method3", "method4"],
  featured: true,
  date: "date string here",
  author: "Yorick",
  tags: ["tag1", "tag2", "tag3"],
  difficulty: 3,
  cookTime: "1 Hour",
  prepTime: "20 minutes",
  servingSize: 4,
  numberOfComments: 0,
  numberOfFavorites: 2,
  typeOfPost: "Recipe"

}, {
  title: "post title 44444",
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia voluptatibus perspiciatis, minima culpa modi vero labore aut dignissimos quas fugiat corporis ipsam eligendi hic a aliquid ducimus optio, veritatis dicta.",
  ingredients: ["ingredient1", "ingredient2", "ingredient3", "ingredient4"],
  method: ["method1", "method2", "method3", "method4"],
  featured: true,
  date: "date string here",
  author: "Yorick",
  tags: ["tag1", "tag2", "tag3"],
  difficulty: 3,
  cookTime: "1 Hour",
  prepTime: "20 minutes",
  servingSize: 4,
  numberOfComments: 0,
  numberOfFavorites: 2,
  typeOfPost: "Recipe"

}, {
  title: "post title 55555",
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia voluptatibus perspiciatis, minima culpa modi vero labore aut dignissimos quas fugiat corporis ipsam eligendi hic a aliquid ducimus optio, veritatis dicta.",
  ingredients: ["ingredient1", "ingredient2", "ingredient3", "ingredient4"],
  method: ["method1", "method2", "method3", "method4"],
  featured: true,
  date: "date here",
  author: "Yorick",
  tags: ["tag1", "tag2", "tag3"],
  difficulty: 3,
  cookTime: "1 Hour",
  prepTime: "20 minutes",
  servingSize: 4,
  numberOfComments: 0,
  numberOfFavorites: 2,
  typeOfPost: "Recipe",
}]
