[
  {
    _id: {
      $oid: '642197e12921c53976c16a40',
    },
    title: 'Raspberry cake with Cream',
    description: 'quick raspberry pie',
    ingredients: ['raspberries', 'cream', 'sponge cake'],
    method: [
      'whip the cream',
      'cut the spongecake and spread the cream and raspberries inside',
    ],
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1680016074/veganPlusButter/rvenff2v7h9r3twxj9kh.avif',
    ],
    date: '11/11/2023, 09:49:43',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['easy', 'baking', 'dessert'],
    difficulty: 2,
    cookTime: '0',
    prepTime: '20',
    servingSize: 6,
    createdAt: {
      $date: '2023-03-27T13:19:29.222Z',
    },
    updatedAt: {
      $date: '2023-11-11T08:49:43.270Z',
    },
    __v: 0,
    featured: false,
  },
  {
    _id: {
      $oid: '642198c62921c53976c16a53',
    },
    title: 'Tasty Bowl',
    description:
      'super tasty bowl of delcious vegetables that can be consumned by a human because a human eats food',
    ingredients: ['2 eggs', 'tofu', 'lettuce', 'corn', 'cucumber'],
    method: [
      'chop everything up',
      'add the ingredients to a bowl',
      'CONSUME!!!',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1680016074/veganPlusButter/rvenff2v7h9r3twxj9kh.avif',
    ],
    date: '25/04/2023, 12:52:01',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['easy', 'vegetarian', 'lunch'],
    difficulty: 2,
    cookTime: '0',
    prepTime: '15',
    servingSize: 2,
    createdAt: {
      $date: '2023-03-27T13:23:18.209Z',
    },
    updatedAt: {
      $date: '2023-04-25T10:52:01.413Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6421a12c2921c53976c16aba',
    },
    title: 'Pizza',
    description:
      'Make this pizza when your feeling hungry and have a little bit of time to spare. Its very much worth the effort and the wait!',
    ingredients: ['flour', 'cheese', 'tomatos', 'onions', 'yeast'],
    method: [
      'make the dough',
      'add the tomato sauce',
      'spread the cheese onto the tomato sauce',
      'add the toppings',
      'bake for 10-12 minutes',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1679576156/veganPlusButter/yaneeyhlrqugyt8cpml1.avif',
    ],
    date: '09/08/2023, 15:47:11',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['hard', 'vegetarian', 'dinner'],
    difficulty: 2,
    cookTime: '12',
    prepTime: '120',
    servingSize: 2,
    createdAt: {
      $date: '2023-03-27T13:59:08.853Z',
    },
    updatedAt: {
      $date: '2023-08-09T13:47:11.997Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6421a1862921c53976c16ad3',
    },
    title: 'Vegan Pancakes',
    description:
      'tasty little vegan pancakes that you can whip up quickly and have a tasty little snack',
    ingredients: ['bananas', 'flour', 'milk', 'Buter'],
    method: ['add dry ingredients together', 'mix in the wet ingredients'],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1680016448/veganPlusButter/pybpaotvna2o7ty6wdmk.avif',
    ],
    date: '04/05/2023, 12:24:06',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['easy', 'vegan', 'quick'],
    difficulty: 1,
    cookTime: '10',
    prepTime: '10',
    servingSize: 2,
    createdAt: {
      $date: '2023-03-27T14:00:38.169Z',
    },
    updatedAt: {
      $date: '2023-05-04T10:24:06.369Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6423011ded0b0caff28f33ec',
    },
    title: 'Salad',
    description: 'here is a tasty salad to throw together real quick',
    ingredients: ['lettuce', 'tomato', 'avocado', 'red cabbage', 'chickpeas'],
    method: [
      'chop up all the ingredients',
      'put them in a bowl',
      'Your ready to eat!',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1680017055/veganPlusButter/xscre2yknef6xsftd8hi.avif',
    ],
    date: '04/05/2023, 12:19:15',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['easy', 'vegan', 'lunch'],
    difficulty: 1,
    cookTime: '0',
    prepTime: '10',
    servingSize: 1,
    createdAt: {
      $date: '2023-03-28T15:00:45.493Z',
    },
    updatedAt: {
      $date: '2023-05-04T10:19:15.740Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '642439550d109d7fdec7bba5',
    },
    title: 'French Toast',
    description:
      'My go to saturday morning recipe when I have some leftover old bread. whips up super easy with a bunch of maple syrup, blueberries and bananas.',
    ingredients: ['day old bread', 'eggs', 'milk', 'bananas', 'blueberries'],
    method: [
      'SOak the bread in the egg and milk mixture',
      'fry in the pan with a neutral oil or some butter',
      'serve fresh together with lots of bananas and blue berries',
    ],
    featured: false,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1680094576/veganPlusButter/zdkf2i7phxqsimpnncl9.avif',
    ],
    date: '02/09/2023, 15:40:43',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['intermediate', 'breakfast'],
    difficulty: 2,
    cookTime: '10',
    prepTime: '25',
    servingSize: 2,
    createdAt: {
      $date: '2023-03-29T13:12:53.939Z',
    },
    updatedAt: {
      $date: '2023-09-02T13:40:43.535Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6424a03ef7e3c646566344f5',
    },
    title: '3 Ingredients Chocolate Mousse',
    description:
      'Super quick and easy sugarfree yet delicious vegan Chocolote Mousse.',
    ingredients: [
      '100g Unsweetened chocolate (100% cacao)',
      '2 Cups non-dairy milk milk ',
      '1 Cup Medjool dates',
    ],
    method: [
      'Bring a pot of water to boil. \n',
      'Chop the chocolate into small chunks and melt over the pot of hot water, making sure that the water is not too hot (50-60°C).',
      'In a blender, combine the almond milk and dates. Blend on high until smooth.',
      'Add the melted chocolate and blend again until combined.',
      'Pour into small bowls or jars. Refrigerate for at least 4 hours until set.',
    ],
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1680121692/veganPlusButter/c9b94bul6836ry9rlpf5.avif',
    ],
    date: '31/03/2023, 10:16:44',
    author: {
      $oid: '641b1f967802748b4ad2e711',
    },
    tags: ['vegan', 'easy', 'dessert', 'quick'],
    difficulty: 1,
    cookTime: '20',
    prepTime: '10',
    servingSize: 6,
    createdAt: {
      $date: '2023-03-29T20:31:58.569Z',
    },
    updatedAt: {
      $date: '2023-03-31T08:16:44.967Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '644799ad489831d83df0da8c',
    },
    title: 'test updated time',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque venenatis vitae leo et auctor. Quisque tincidunt volutpat quam, non interdum sapien hendrerit vel. Vivamus mattis, mauris quis convallis mollis, magna elit varius ante, in consectetur felis est commodo turpis. Proin nec pharetra elit. Vestibulum felis turpis, luctus non congue quis, pharetra nec metus. Vivamus a odio nunc. Quisque eget faucibus lorem, eget lobortis erat. Praesent ac justo elit. Pellentesque ut gravida arcu. Mauris vehicula diam nec neque fringilla, non convallis enim dictum. Nullam nec mattis ligula, nec vehicula erat. Phasellus dolor orci, ullamcorper mattis dapibus nec, sagittis quis ligula. Pellentesque ut consectetur ligula, sed ultricies risus. Fusce lacus turpis, viverra vitae diam id, ullamcorper mollis velit. Nunc eu pharetra risus. Nulla non mauris non enim ultrices dictum ut quis quam.\n\n\nMauris sed efficitur velit. Vestibulum blandit euismod lectus, quis elementum ligula elementum sed. Donec interdum a mauris vel efficitur. Morbi pretium erat eget ligula rhoncus rhoncus. Proin condimentum ante sed mauris tincidunt lobortis. Vivamus sollicitudin metus nibh, eu bibendum odio semper et. Ut egestas pulvinar sem at maximus. Integer in diam sit amet risus aliquam condimentum eu quis urna.\n\n\nEtiam dictum, elit id facilisis vulputate, neque mauris ultricies quam, nec consectetur elit lectus at nibh. Vestibulum neque turpis, sodales a erat vel, suscipit sodales lacus. Mauris gravida leo enim, et ornare metus facilisis eget. Nulla sit amet turpis molestie, sodales eros non, dapibus tortor. Etiam leo tellus, suscipit eu leo at, auctor pellentesque nisi. Nunc rhoncus scelerisque turpis eu facilisis. Nam ut metus vel urna sodales tempor. Sed vel ligula lectus. Proin sollicitudin consequat nibh, vitae ultrices tellus sollicitudin a. Pellentesque fermentum ex ac odio aliquam, ac ornare enim vulputate. Sed nunc dolor, consequat vel aliquam a, sollicitudin quis nunc. Pellentesque mi dolor, tristique congue odio vel, lobortis ornare arcu. Donec quis varius lorem.\n\n\nEtiam nisi odio, rutrum at laoreet et, cursus nec dolor. Maecenas vulputate accumsan erat. Quisque sit amet mauris ac risus cursus vestibulum a vitae mauris. Cras imperdiet, est at imperdiet auctor, augue eros rutrum mauris, et vulputate ex lacus sit amet neque. Integer accumsan tortor consequat, ultricies nibh eget, tempor odio. Ut sit amet nulla ut quam molestie accumsan. Phasellus sodales mi eros, rutrum pretium dui interdum ac. Cras aliquam lobortis augue sed vestibulum. Donec faucibus in libero non fermentum.\n\n\nQuisque malesuada vitae turpis in tempus. Aenean dui lacus, aliquet sit amet eros ut, gravida egestas leo. Sed ac scelerisque velit. Integer condimentum mi lorem, quis fringilla erat gravida sed. In hac habitasse platea dictumst. Vestibulum justo dolor, maximus sit amet justo et, vehicula faucibus tellus. Vestibulum et tellus tortor. Pellentesque eget vestibulum risus. Mauris tincidunt neque eu pretium scelerisque. Quisque accumsan malesuada lectus id pharetra. Proin ut elementum nibh. Nunc consequat dictum congue. Cras eget pellentesque odio. Donec id sem lacus. Nunc ut malesuada sapien.',
    ingredients: [],
    method: [],
    images: [],
    date: '25/04/2023, 14:40:28',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['Blog Post'],
    createdAt: {
      $date: '2023-04-25T09:13:17.281Z',
    },
    updatedAt: {
      $date: '2023-04-25T12:40:28.646Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6447c988489831d83df0ddf1',
    },
    title: 'noedit',
    description:
      'Donec ullamcorper tempus eros ut consequat. Nunc sapien enim, blandit quis magna nec, sodales tempor risus. Maecenas a lacinia justo. Nulla pretium dapibus ligula sit amet suscipit. Vestibulum lacinia tincidunt ligula, sed cursus diam hendrerit in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse mollis congue ex porttitor placerat. Nam vitae convallis augue. Suspendisse dapibus mi gravida tellus maximus porta. Vivamus cursus lectus libero, a ornare nulla dignissim in. Vestibulum id laoreet nisl. Aliquam mi velit, tempor non mollis non, ultrices vulputate justo.\n\nAliquam non vestibulum ante. Suspendisse vestibulum elit tortor, in vehicula nunc mattis in. Vestibulum nisi ex, mattis nec aliquam a, euismod in dolor. Maecenas eu tortor vel augue dignissim aliquet eget eu libero. Cras sit amet consequat dolor. Proin eu tellus aliquam, rutrum urna a, porta nibh. Aenean et enim quis metus dapibus convallis. Aliquam sagittis libero eget purus vestibulum vehicula. Nullam vitae nisl pretium, blandit eros ac, finibus justo. Nulla dictum semper elit. Donec volutpat ligula non enim faucibus, eu venenatis dolor commodo. Nullam ultrices elementum ornare. Morbi dignissim, purus vel dictum fringilla, diam odio dictum lorem, et dignissim diam justo efficitur neque. Integer porta commodo ante id euismod. Morbi quis pretium nisi, sed hendrerit tellus. Duis sit amet magna elit.\n\nPellentesque nunc purus, euismod in dui sed, suscipit tristique justo. Vestibulum fringilla lacus quis neque egestas, ac efficitur felis rhoncus. Maecenas finibus, elit at vulputate dapibus, nibh turpis molestie nibh, ac dictum justo neque a ante. Duis eu odio ac metus porta bibendum et ut augue. Curabitur commodo euismod tellus, ut feugiat dolor laoreet id. Duis vitae euismod massa. In pellentesque ut quam non lobortis.\n\nCras dictum libero non mi molestie, et rhoncus sem condimentum. Phasellus placerat condimentum nulla non molestie. Nulla facilisi. Mauris lectus est, fermentum sit amet sapien sit amet, dictum cursus enim. Sed molestie egestas nisi, id blandit purus pharetra nec. Etiam posuere iaculis mi, vel fringilla nisi porta eget. Curabitur bibendum elit nec posuere fermentum. Donec vel condimentum eros, sit amet dapibus elit. Sed id gravida dui. Vivamus aliquam ante ac dictum ultricies. Integer a ex dictum, vestibulum nibh id, congue nibh.\n\nAliquam erat volutpat. Morbi tempus erat in nulla iaculis varius. Cras id risus eu eros aliquet fermentum a posuere lorem. Morbi dignissim enim quis sapien commodo sollicitudin. Aenean iaculis pellentesque quam. Vestibulum mi erat, porta at maximus nec, feugiat et justo. Duis leo mi, aliquam at ante et, viverra pulvinar magna. Donec vitae nulla iaculis, hendrerit metus eget, bibendum lacus. Vestibulum ullamcorper suscipit viverra. Proin eu erat sollicitudin, lobortis justo id, iaculis lorem. Nunc vitae ante est. Aenean dignissim mauris ac nibh suscipit, maximus consectetur risus fermentum. In quis est a nunc varius pretium. Curabitur commodo, urna ut rhoncus molestie, eros turpis iaculis tortor, eget laoreet risus libero congue mi. Sed id ex elementum, laoreet nisl at, gravida est. Nam luctus libero in lacus egestas suscipit.',
    ingredients: [],
    method: [],
    images: [],
    date: '25/04/2023, 15:59:26',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['Blog Post'],
    createdAt: {
      $date: '2023-04-25T12:37:28.297Z',
    },
    updatedAt: {
      $date: '2023-04-25T13:59:26.683Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '654e43f47a50ab1379f831e4',
    },
    title: 'newest Blog Post',
    description: 'long description about a blog post',
    ingredients: [''],
    method: [''],
    images: [],
    date: '10/11/2023, 15:53:40',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['Blog Post'],
    createdAt: {
      $date: '2023-11-10T14:53:40.928Z',
    },
    updatedAt: {
      $date: '2023-11-10T14:53:40.928Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c1a',
    },
    title: 'Vegan Lentil Curry',
    description:
      'A hearty and flavorful vegan lentil curry with a blend of aromatic spices.',
    ingredients: [
      '1 cup dried lentils',
      '1 can coconut milk',
      '1 onion, finely chopped',
      '3 cloves garlic, minced',
      '1 tablespoon curry powder',
      '1 teaspoon cumin',
      '1 teaspoon turmeric',
      '1 can diced tomatoes',
      'Salt and pepper to taste',
    ],
    method: [
      'Rinse lentils and cook according to package instructions.',
      'In a pot, sauté onions and garlic until translucent.',
      'Add curry powder, cumin, and turmeric, and cook for another minute.',
      'Stir in cooked lentils, coconut milk, and diced tomatoes.',
      'Simmer until flavors meld, season with salt and pepper.',
      'Serve hot over rice.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414411/veganPlusButter/figs_ww7clh.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['vegan', 'dinner', 'healthy'],
    difficulty: 2,
    cookTime: '40 minutes',
    prepTime: '15 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c1b',
    },
    title: 'Quinoa Salad with Roasted Vegetables',
    description:
      'A nutritious and colorful quinoa salad featuring a variety of roasted vegetables.',
    ingredients: [
      '1 cup quinoa, cooked',
      '1 bell pepper, diced',
      '1 zucchini, sliced',
      '1 cup cherry tomatoes, halved',
      '1 red onion, finely chopped',
      '2 tablespoons olive oil',
      '1 teaspoon dried oregano',
      'Salt and black pepper to taste',
      'Feta cheese for garnish',
    ],
    method: [
      'Preheat the oven to 400°F (200°C).',
      'Toss bell pepper, zucchini, cherry tomatoes, and red onion with olive oil and oregano.',
      'Spread the vegetables on a baking sheet and roast for 20-25 minutes.',
      'In a large bowl, mix the roasted vegetables with cooked quinoa.',
      'Season with salt and pepper, garnish with feta cheese, and serve chilled.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414408/veganPlusButter/pastas_gup6om.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['vegetarian', 'easy', 'healthy'],
    difficulty: 2,
    cookTime: '30 minutes',
    prepTime: '15 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c1c',
    },
    title: 'Spaghetti Aglio e Olio',
    description:
      'A classic Italian pasta dish with a simple yet delicious garlic and olive oil sauce.',
    ingredients: [
      '8 oz spaghetti',
      '4 cloves garlic, thinly sliced',
      '1/2 teaspoon red pepper flakes',
      '1/4 cup olive oil',
      'Chopped parsley for garnish',
      'Grated Parmesan cheese',
      'Salt to taste',
    ],
    method: [
      'Cook spaghetti according to package instructions.',
      'In a pan, sauté garlic and red pepper flakes in olive oil until garlic is golden.',
      'Toss cooked spaghetti in the garlic and oil mixture.',
      'Season with salt, garnish with parsley, and serve with Parmesan cheese.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414408/veganPlusButter/pastas_gup6om.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['healthy', 'vegan', 'dinner'],
    difficulty: 1,
    cookTime: '15 minutes',
    prepTime: '10 minutes',
    servingSize: 2,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c1d',
    },
    title: 'Crispy Baked Chicken Tenders',
    description:
      'Homemade crispy chicken tenders that are baked to perfection, a healthier alternative to frying.',
    ingredients: [
      '1 lb chicken tenders',
      '1 cup breadcrumbs',
      '1/2 cup grated Parmesan cheese',
      '1 teaspoon garlic powder',
      '1 teaspoon paprika',
      'Salt and black pepper to taste',
      '1/2 cup flour',
      '2 eggs, beaten',
    ],
    method: [
      'Preheat the oven to 400°F (200°C).',
      'In one bowl, mix breadcrumbs, Parmesan, garlic powder, paprika, salt, and pepper.',
      'Dip each chicken tender in flour, then egg, and coat with breadcrumb mixture.',
      'Place tenders on a baking sheet and bake for 20-25 minutes until golden and crispy.',
      'Serve hot with your favorite dipping sauce.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414406/veganPlusButter/tacos_aiztvd.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['quick', 'dinner'],
    difficulty: 2,
    cookTime: '25 minutes',
    prepTime: '15 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c1e',
    },
    title: 'Blueberry Oatmeal Muffins',
    description:
      'Moist and flavorful blueberry muffins made with wholesome oats.',
    ingredients: [
      '1 cup rolled oats',
      '1 cup buttermilk',
      '1 cup all-purpose flour',
      '1 teaspoon baking powder',
      '1/2 teaspoon baking soda',
      '1/2 cup unsalted butter, melted',
      '1/2 cup brown sugar',
      '1 egg',
      '1 cup blueberries (fresh or frozen)',
    ],
    method: [
      'Preheat the oven to 375°F (190°C).',
      'In a bowl, soak oats in buttermilk for 15 minutes.',
      'In another bowl, mix flour, baking powder, and baking soda.',
      'Add melted butter, brown sugar, and egg to the oat mixture.',
      'Combine wet and dry ingredients, then fold in blueberries.',
      'Spoon batter into muffin cups and bake for 20-25 minutes.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414406/veganPlusButter/pesto_eks50n.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['breakfast', 'baking'],
    difficulty: 2,
    cookTime: '25 minutes',
    prepTime: '15 minutes',
    servingSize: 12,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c1f',
    },
    title: 'Mango Salsa Chicken',
    description: 'Grilled chicken topped with a fresh and tangy mango salsa.',
    ingredients: [
      '4 boneless, skinless chicken breasts',
      '1 ripe mango, diced',
      '1/2 red onion, finely chopped',
      '1 jalapeño, seeded and minced',
      'Juice of 2 limes',
      '1/4 cup fresh cilantro, chopped',
      'Salt and black pepper to taste',
    ],
    method: [
      'Preheat the grill to medium-high heat.',
      'Season chicken breasts with salt and pepper.',
      'Grill the chicken until fully cooked, about 6-8 minutes per side.',
      'In a bowl, combine diced mango, red onion, jalapeño, lime juice, and cilantro to make the salsa.',
      'Top grilled chicken with mango salsa and serve hot.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414406/veganPlusButter/meatballs_pyvx4z.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['dinner', 'healthy'],
    difficulty: 2,
    cookTime: '16 minutes',
    prepTime: '15 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c20',
    },
    title: 'Chocolate Avocado Smoothie',
    description:
      'A creamy and decadent chocolate smoothie with the goodness of avocado.',
    ingredients: [
      '1 ripe avocado, peeled and pitted',
      '1 banana',
      '2 tablespoons cocoa powder',
      '1 cup almond milk',
      '1 tablespoon honey or maple syrup',
      '1/2 teaspoon vanilla extract',
      'Ice cubes',
    ],
    method: [
      'In a blender, combine avocado, banana, cocoa powder, almond milk, honey or maple syrup, and vanilla extract.',
      'Blend until smooth and creamy.',
      'Add ice cubes and blend again until well combined.',
      'Pour into glasses and enjoy this healthy chocolate treat.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414405/veganPlusButter/isecream_ihlwwa.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['snack', 'healthy'],
    difficulty: 1,
    cookTime: '5 minutes',
    prepTime: '5 minutes',
    servingSize: 2,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c21',
    },
    title: 'Stuffed Bell Peppers',
    description:
      'Colorful bell peppers stuffed with a flavorful mixture of quinoa, black beans, and vegetables.',
    ingredients: [
      '4 bell peppers, halved and seeds removed',
      '1 cup cooked quinoa',
      '1 can black beans, drained and rinsed',
      '1 cup corn kernels',
      '1 cup cherry tomatoes, diced',
      '1/2 cup shredded cheddar cheese',
      '1 teaspoon cumin',
      '1/2 teaspoon chili powder',
      'Salt and black pepper to taste',
    ],
    method: [
      'Preheat the oven to 375°F (190°C).',
      'In a bowl, mix cooked quinoa, black beans, corn, tomatoes, cheese, cumin, chili powder, salt, and pepper.',
      'Stuff each bell pepper half with the quinoa mixture.',
      'Place stuffed peppers in a baking dish and bake for 25-30 minutes.',
      'Serve hot and enjoy this wholesome dish.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414405/veganPlusButter/burger_unegiq.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['dinner', 'vegetarian', 'healthy'],
    difficulty: 2,
    cookTime: '30 minutes',
    prepTime: '20 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c22',
    },
    title: 'Pesto Pasta with Sun-Dried Tomatoes',
    description:
      'Delicious pasta tossed in a vibrant pesto sauce with sun-dried tomatoes for extra flavor.',
    ingredients: [
      '8 oz pasta of your choice',
      '1 cup fresh basil leaves',
      '1/2 cup grated Parmesan cheese',
      '1/3 cup pine nuts',
      '2 cloves garlic',
      '1/2 cup sun-dried tomatoes, chopped',
      '1/2 cup olive oil',
      'Salt and black pepper to taste',
    ],
    method: [
      'Cook pasta according to package instructions.',
      'In a food processor, blend basil, Parmesan, pine nuts, garlic, and sun-dried tomatoes.',
      'While blending, slowly add olive oil until a smooth pesto sauce forms.',
      'Toss cooked pasta with the pesto sauce, season with salt and pepper.',
      'Serve warm and enjoy this flavorful dish.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414406/veganPlusButter/pesto_eks50n.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['easy', 'lunch', 'quick'],
    difficulty: 2,
    cookTime: '15 minutes',
    prepTime: '10 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c23',
    },
    title: 'Avocado Toast with Poached Egg',
    description:
      'A simple and nutritious breakfast featuring creamy avocado on crispy toast with a perfectly poached egg on top.',
    ingredients: [
      '2 slices whole-grain bread',
      '1 ripe avocado, mashed',
      '2 eggs',
      'Salt and black pepper to taste',
      'Red pepper flakes for garnish',
      'Chopped chives for garnish',
    ],
    method: [
      'Toast the bread slices until golden and crispy.',
      'Spread mashed avocado evenly on each toast slice.',
      'In a pot of simmering water, poach the eggs until the whites are set but the yolks remain runny.',
      'Carefully place a poached egg on top of each avocado toast.',
      'Season with salt, black pepper, and garnish with red pepper flakes and chopped chives.',
      'Serve immediately for a delicious and satisfying breakfast.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414405/veganPlusButter/burger_unegiq.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['breakfast', 'healthy'],
    difficulty: 1,
    cookTime: '10 minutes',
    prepTime: '10 minutes',
    servingSize: 2,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c24',
    },
    title: 'Mediterranean Chickpea Salad',
    description:
      'A refreshing salad with chickpeas, cucumbers, cherry tomatoes, and feta cheese, tossed in a lemon-herb dressing.',
    ingredients: [
      '1 can chickpeas, drained and rinsed',
      '1 cucumber, diced',
      '1 cup cherry tomatoes, halved',
      '1/2 red onion, finely chopped',
      '1/2 cup feta cheese, crumbled',
      '1/4 cup Kalamata olives, sliced',
      '2 tablespoons olive oil',
      'Juice of 1 lemon',
      '1 teaspoon dried oregano',
      'Salt and black pepper to taste',
    ],
    method: [
      'In a large bowl, combine chickpeas, cucumber, cherry tomatoes, red onion, feta cheese, and olives.',
      'In a small bowl, whisk together olive oil, lemon juice, oregano, salt, and black pepper.',
      'Pour the dressing over the salad and toss until well coated.',
      'Chill in the refrigerator for at least 30 minutes before serving.',
      'Enjoy this Mediterranean-inspired salad as a light and satisfying meal.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414411/veganPlusButter/figs_ww7clh.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['Salad', 'Vegetarian', 'Quick'],
    difficulty: 1,
    cookTime: '10 minutes',
    prepTime: '15 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c25',
    },
    title: 'Pumpkin Spice Pancakes',
    description:
      'Fluffy and delicious pancakes infused with warm pumpkin spice flavors, perfect for a cozy breakfast.',
    ingredients: [
      '1 cup all-purpose flour',
      '2 tablespoons sugar',
      '1 teaspoon baking powder',
      '1/2 teaspoon baking soda',
      '1/2 teaspoon pumpkin spice',
      '1/2 cup canned pumpkin puree',
      '1 cup buttermilk',
      '1 egg',
      '2 tablespoons melted butter',
      'Maple syrup for serving',
    ],
    method: [
      'In a bowl, whisk together flour, sugar, baking powder, baking soda, and pumpkin spice.',
      'In another bowl, mix pumpkin puree, buttermilk, egg, and melted butter.',
      'Combine wet and dry ingredients, stirring until just combined.',
      'Heat a griddle or non-stick pan over medium heat.',
      'Pour batter onto the griddle to form pancakes and cook until bubbles form on the surface.',
      'Flip and cook until golden brown. Serve with maple syrup.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414408/veganPlusButter/pastas_gup6om.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['Breakfast', 'Dessert', 'Fall'],
    difficulty: 2,
    cookTime: '15 minutes',
    prepTime: '10 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c8037ba3ba91b5a62c26',
    },
    title: 'Garlic Butter Shrimp Pasta',
    description:
      'A decadent pasta dish featuring succulent garlic butter shrimp tossed with linguine.',
    ingredients: [
      '8 oz linguine',
      '1 lb large shrimp, peeled and deveined',
      '4 cloves garlic, minced',
      '2 tablespoons unsalted butter',
      '1/2 cup chicken broth',
      'Juice of 1 lemon',
      'Chopped parsley for garnish',
      'Salt and black pepper to taste',
      'Grated Parmesan cheese for serving',
    ],
    method: [
      'Cook linguine according to package instructions.',
      'Season shrimp with salt and black pepper.',
      'In a pan, melt butter and sauté garlic until fragrant.',
      'Add shrimp and cook until pink and opaque.',
      'Pour in chicken broth and lemon juice, simmer until slightly reduced.',
      'Toss cooked linguine in the garlic butter shrimp mixture, garnish with parsley.',
      'Serve hot with a sprinkle of grated Parmesan cheese.',
    ],
    featured: true,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414408/veganPlusButter/pastas_gup6om.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['Italian', 'Seafood', 'Dinner'],
    difficulty: 2,
    cookTime: '20 minutes',
    prepTime: '15 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c9957ba3ba91b5a62c28',
    },
    title: 'Quinoa Salad with Roasted Vegetables',
    description:
      'A hearty quinoa salad with a medley of roasted vegetables, perfect for a satisfying lunch.',
    ingredients: [
      '1 cup quinoa, cooked',
      '1 zucchini, diced',
      '1 red bell pepper, sliced',
      '1 yellow bell pepper, sliced',
      '1 cup cherry tomatoes, halved',
      '1/4 cup feta cheese, crumbled',
      '2 tablespoons olive oil',
      '1 tablespoon balsamic vinegar',
      'Salt and black pepper to taste',
    ],
    method: [
      'Preheat the oven to 400°F (200°C).',
      'In a baking pan, toss diced zucchini, sliced red and yellow bell peppers with olive oil, salt, and black pepper.',
      'Roast the vegetables in the preheated oven for 20-25 minutes or until tender and slightly caramelized.',
      'In a large bowl, combine cooked quinoa, roasted vegetables, cherry tomatoes, and crumbled feta cheese.',
      'Drizzle with balsamic vinegar, toss gently, and serve this flavorful quinoa salad for a delicious lunch option.',
    ],
    featured: false,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414411/veganPlusButter/figs_ww7clh.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['Lunch', 'Vegetarian', 'Healthy'],
    difficulty: 2,
    cookTime: '30 minutes',
    prepTime: '15 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c9957ba3ba91b5a62c29',
    },
    title: 'Chicken Avocado Wrap',
    description:
      'A quick and delicious chicken avocado wrap, perfect for a tasty and fulfilling lunch on the go.',
    ingredients: [
      '1 boneless, skinless chicken breast, grilled and sliced',
      '1 large avocado, sliced',
      '1 cup mixed greens',
      '2 tablespoons Greek yogurt',
      '1 teaspoon Dijon mustard',
      '4 whole wheat tortillas',
    ],
    method: [
      'In a small bowl, mix Greek yogurt and Dijon mustard to create a creamy dressing.',
      'Spread the dressing over each whole wheat tortilla.',
      'Layer sliced grilled chicken, avocado, and mixed greens on each tortilla.',
      'Fold the sides of the tortilla and roll tightly to create a wrap.',
      'Slice in half and enjoy this flavorful and nutritious chicken avocado wrap for your lunch.',
    ],
    featured: false,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414406/veganPlusButter/tacos_aiztvd.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['Lunch', 'Intermediate', 'Quick'],
    difficulty: 2,
    cookTime: '15 minutes',
    prepTime: '10 minutes',
    servingSize: 2,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554c9957ba3ba91b5a62c2a',
    },
    title: 'Mushroom and Spinach Quesadillas',
    description:
      'Delicious mushroom and spinach quesadillas with melted cheese, a perfect lunch option for a quick and satisfying meal.',
    ingredients: [
      '8 small flour tortillas',
      '2 cups mushrooms, sliced',
      '2 cups fresh spinach',
      '1 cup shredded cheddar cheese',
      '1 tablespoon olive oil',
      '1 teaspoon cumin',
      '1/2 teaspoon paprika',
      'Salt and black pepper to taste',
      'Salsa and sour cream for serving',
    ],
    method: [
      'In a pan, heat olive oil over medium heat.',
      'Add sliced mushrooms and sauté until they release their moisture and become golden brown.',
      'Add fresh spinach to the pan and cook until wilted.',
      'Season with cumin, paprika, salt, and black pepper.',
      'Place a tortilla in the pan, add a layer of the mushroom and spinach mixture, sprinkle with shredded cheddar cheese, and top with another tortilla.',
      'Cook until the cheese is melted and the tortillas are golden brown on both sides.',
      'Repeat with the remaining ingredients.',
      'Slice into wedges and serve with salsa and sour cream.',
    ],
    featured: false,
    images: [
      'https://res.cloudinary.com/yozzza/image/upload/v1698414405/veganPlusButter/burger_unegiq.avif',
    ],
    date: '2023-10-27',
    author: '64fb2bb32fc8149bf0d4b25a',
    tags: ['Lunch', 'Easy', 'Vegetarian'],
    difficulty: 3,
    cookTime: '20 minutes',
    prepTime: '15 minutes',
    servingSize: 4,
    numberOfComments: 0,
    numberOfFavorites: 0,
    typeOfPost: 'Recipe',
  },
  {
    _id: {
      $oid: '6554cb967ba3ba91b5a62c2b',
    },
    title: 'noedit2',
    description:
      'Donec ullamcorper tempus eros ut consequat. Nunc sapien enim, blandit quis magna nec, sodales tempor risus. Maecenas a lacinia justo. Nulla pretium dapibus ligula sit amet suscipit. Vestibulum lacinia tincidunt ligula, sed cursus diam hendrerit in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse mollis congue ex porttitor placerat. Nam vitae convallis augue. Suspendisse dapibus mi gravida tellus maximus porta. Vivamus cursus lectus libero, a ornare nulla dignissim in. Vestibulum id laoreet nisl. Aliquam mi velit, tempor non mollis non, ultrices vulputate justo.\n\nAliquam non vestibulum ante. Suspendisse vestibulum elit tortor, in vehicula nunc mattis in. Vestibulum nisi ex, mattis nec aliquam a, euismod in dolor. Maecenas eu tortor vel augue dignissim aliquet eget eu libero. Cras sit amet consequat dolor. Proin eu tellus aliquam, rutrum urna a, porta nibh. Aenean et enim quis metus dapibus convallis. Aliquam sagittis libero eget purus vestibulum vehicula. Nullam vitae nisl pretium, blandit eros ac, finibus justo. Nulla dictum semper elit. Donec volutpat ligula non enim faucibus, eu venenatis dolor commodo. Nullam ultrices elementum ornare. Morbi dignissim, purus vel dictum fringilla, diam odio dictum lorem, et dignissim diam justo efficitur neque. Integer porta commodo ante id euismod. Morbi quis pretium nisi, sed hendrerit tellus. Duis sit amet magna elit.\n\nPellentesque nunc purus, euismod in dui sed, suscipit tristique justo. Vestibulum fringilla lacus quis neque egestas, ac efficitur felis rhoncus. Maecenas finibus, elit at vulputate dapibus, nibh turpis molestie nibh, ac dictum justo neque a ante. Duis eu odio ac metus porta bibendum et ut augue. Curabitur commodo euismod tellus, ut feugiat dolor laoreet id. Duis vitae euismod massa. In pellentesque ut quam non lobortis.\n\nCras dictum libero non mi molestie, et rhoncus sem condimentum. Phasellus placerat condimentum nulla non molestie. Nulla facilisi. Mauris lectus est, fermentum sit amet sapien sit amet, dictum cursus enim. Sed molestie egestas nisi, id blandit purus pharetra nec. Etiam posuere iaculis mi, vel fringilla nisi porta eget. Curabitur bibendum elit nec posuere fermentum. Donec vel condimentum eros, sit amet dapibus elit. Sed id gravida dui. Vivamus aliquam ante ac dictum ultricies. Integer a ex dictum, vestibulum nibh id, congue nibh.\n\nAliquam erat volutpat. Morbi tempus erat in nulla iaculis varius. Cras id risus eu eros aliquet fermentum a posuere lorem. Morbi dignissim enim quis sapien commodo sollicitudin. Aenean iaculis pellentesque quam. Vestibulum mi erat, porta at maximus nec, feugiat et justo. Duis leo mi, aliquam at ante et, viverra pulvinar magna. Donec vitae nulla iaculis, hendrerit metus eget, bibendum lacus. Vestibulum ullamcorper suscipit viverra. Proin eu erat sollicitudin, lobortis justo id, iaculis lorem. Nunc vitae ante est. Aenean dignissim mauris ac nibh suscipit, maximus consectetur risus fermentum. In quis est a nunc varius pretium. Curabitur commodo, urna ut rhoncus molestie, eros turpis iaculis tortor, eget laoreet risus libero congue mi. Sed id ex elementum, laoreet nisl at, gravida est. Nam luctus libero in lacus egestas suscipit.',
    ingredients: [],
    method: [],
    images: [],
    date: '25/04/2023, 15:59:26',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['Blog Post'],
    createdAt: {
      $date: '2023-04-25T12:37:28.297Z',
    },
    updatedAt: {
      $date: '2023-04-25T13:59:26.683Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6554cbc57ba3ba91b5a62c2c',
    },
    title: 'Long title',
    description:
      'Donec ullamcorper tempus eros ut consequat. Nunc sapien enim, blandit quis magna nec, sodales tempor risus. Maecenas a lacinia justo. Nulla pretium dapibus ligula sit amet suscipit. Vestibulum lacinia tincidunt ligula, sed cursus diam hendrerit in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse mollis congue ex porttitor placerat. Nam vitae convallis augue. Suspendisse dapibus mi gravida tellus maximus porta. Vivamus cursus lectus libero, a ornare nulla dignissim in. Vestibulum id laoreet nisl. Aliquam mi velit, tempor non mollis non, ultrices vulputate justo.\n\nAliquam non vestibulum ante. Suspendisse vestibulum elit tortor, in vehicula nunc mattis in. Vestibulum nisi ex, mattis nec aliquam a, euismod in dolor. Maecenas eu tortor vel augue dignissim aliquet eget eu libero. Cras sit amet consequat dolor. Proin eu tellus aliquam, rutrum urna a, porta nibh. Aenean et enim quis metus dapibus convallis. Aliquam sagittis libero eget purus vestibulum vehicula. Nullam vitae nisl pretium, blandit eros ac, finibus justo. Nulla dictum semper elit. Donec volutpat ligula non enim faucibus, eu venenatis dolor commodo. Nullam ultrices elementum ornare. Morbi dignissim, purus vel dictum fringilla, diam odio dictum lorem, et dignissim diam justo efficitur neque. Integer porta commodo ante id euismod. Morbi quis pretium nisi, sed hendrerit tellus. Duis sit amet magna elit.\n\nPellentesque nunc purus, euismod in dui sed, suscipit tristique justo. Vestibulum fringilla lacus quis neque egestas, ac efficitur felis rhoncus. Maecenas finibus, elit at vulputate dapibus, nibh turpis molestie nibh, ac dictum justo neque a ante. Duis eu odio ac metus porta bibendum et ut augue. Curabitur commodo euismod tellus, ut feugiat dolor laoreet id. Duis vitae euismod massa. In pellentesque ut quam non lobortis.\n\nCras dictum libero non mi molestie, et rhoncus sem condimentum. Phasellus placerat condimentum nulla non molestie. Nulla facilisi. Mauris lectus est, fermentum sit amet sapien sit amet, dictum cursus enim. Sed molestie egestas nisi, id blandit purus pharetra nec. Etiam posuere iaculis mi, vel fringilla nisi porta eget. Curabitur bibendum elit nec posuere fermentum. Donec vel condimentum eros, sit amet dapibus elit. Sed id gravida dui. Vivamus aliquam ante ac dictum ultricies. Integer a ex dictum, vestibulum nibh id, congue nibh.\n\nAliquam erat volutpat. Morbi tempus erat in nulla iaculis varius. Cras id risus eu eros aliquet fermentum a posuere lorem. Morbi dignissim enim quis sapien commodo sollicitudin. Aenean iaculis pellentesque quam. Vestibulum mi erat, porta at maximus nec, feugiat et justo. Duis leo mi, aliquam at ante et, viverra pulvinar magna. Donec vitae nulla iaculis, hendrerit metus eget, bibendum lacus. Vestibulum ullamcorper suscipit viverra. Proin eu erat sollicitudin, lobortis justo id, iaculis lorem. Nunc vitae ante est. Aenean dignissim mauris ac nibh suscipit, maximus consectetur risus fermentum. In quis est a nunc varius pretium. Curabitur commodo, urna ut rhoncus molestie, eros turpis iaculis tortor, eget laoreet risus libero congue mi. Sed id ex elementum, laoreet nisl at, gravida est. Nam luctus libero in lacus egestas suscipit.',
    ingredients: [],
    method: [],
    images: [],
    date: '25/04/2023, 15:59:26',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['Blog Post'],
    createdAt: {
      $date: '2023-04-25T12:37:28.297Z',
    },
    updatedAt: {
      $date: '2023-04-25T13:59:26.683Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6554cbf37ba3ba91b5a62c2d',
    },
    title: 'the art of cooking',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque venenatis vitae leo et auctor. Quisque tincidunt volutpat quam, non interdum sapien hendrerit vel. Vivamus mattis, mauris quis convallis mollis, magna elit varius ante, in consectetur felis est commodo turpis. Proin nec pharetra elit. Vestibulum felis turpis, luctus non congue quis, pharetra nec metus. Vivamus a odio nunc. Quisque eget faucibus lorem, eget lobortis erat. Praesent ac justo elit. Pellentesque ut gravida arcu. Mauris vehicula diam nec neque fringilla, non convallis enim dictum. Nullam nec mattis ligula, nec vehicula erat. Phasellus dolor orci, ullamcorper mattis dapibus nec, sagittis quis ligula. Pellentesque ut consectetur ligula, sed ultricies risus. Fusce lacus turpis, viverra vitae diam id, ullamcorper mollis velit. Nunc eu pharetra risus. Nulla non mauris non enim ultrices dictum ut quis quam.\n\n\nMauris sed efficitur velit. Vestibulum blandit euismod lectus, quis elementum ligula elementum sed. Donec interdum a mauris vel efficitur. Morbi pretium erat eget ligula rhoncus rhoncus. Proin condimentum ante sed mauris tincidunt lobortis. Vivamus sollicitudin metus nibh, eu bibendum odio semper et. Ut egestas pulvinar sem at maximus. Integer in diam sit amet risus aliquam condimentum eu quis urna.\n\n\nEtiam dictum, elit id facilisis vulputate, neque mauris ultricies quam, nec consectetur elit lectus at nibh. Vestibulum neque turpis, sodales a erat vel, suscipit sodales lacus. Mauris gravida leo enim, et ornare metus facilisis eget. Nulla sit amet turpis molestie, sodales eros non, dapibus tortor. Etiam leo tellus, suscipit eu leo at, auctor pellentesque nisi. Nunc rhoncus scelerisque turpis eu facilisis. Nam ut metus vel urna sodales tempor. Sed vel ligula lectus. Proin sollicitudin consequat nibh, vitae ultrices tellus sollicitudin a. Pellentesque fermentum ex ac odio aliquam, ac ornare enim vulputate. Sed nunc dolor, consequat vel aliquam a, sollicitudin quis nunc. Pellentesque mi dolor, tristique congue odio vel, lobortis ornare arcu. Donec quis varius lorem.\n\n\nEtiam nisi odio, rutrum at laoreet et, cursus nec dolor. Maecenas vulputate accumsan erat. Quisque sit amet mauris ac risus cursus vestibulum a vitae mauris. Cras imperdiet, est at imperdiet auctor, augue eros rutrum mauris, et vulputate ex lacus sit amet neque. Integer accumsan tortor consequat, ultricies nibh eget, tempor odio. Ut sit amet nulla ut quam molestie accumsan. Phasellus sodales mi eros, rutrum pretium dui interdum ac. Cras aliquam lobortis augue sed vestibulum. Donec faucibus in libero non fermentum.\n\n\nQuisque malesuada vitae turpis in tempus. Aenean dui lacus, aliquet sit amet eros ut, gravida egestas leo. Sed ac scelerisque velit. Integer condimentum mi lorem, quis fringilla erat gravida sed. In hac habitasse platea dictumst. Vestibulum justo dolor, maximus sit amet justo et, vehicula faucibus tellus. Vestibulum et tellus tortor. Pellentesque eget vestibulum risus. Mauris tincidunt neque eu pretium scelerisque. Quisque accumsan malesuada lectus id pharetra. Proin ut elementum nibh. Nunc consequat dictum congue. Cras eget pellentesque odio. Donec id sem lacus. Nunc ut malesuada sapien.',
    ingredients: [],
    method: [],
    images: [],
    date: '25/04/2023, 14:40:28',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['Blog Post'],
    createdAt: {
      $date: '2023-04-25T09:13:17.281Z',
    },
    updatedAt: {
      $date: '2023-04-25T12:40:28.646Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6554cc027ba3ba91b5a62c2f',
    },
    title: 'Love cooking',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque venenatis vitae leo et auctor. Quisque tincidunt volutpat quam, non interdum sapien hendrerit vel. Vivamus mattis, mauris quis convallis mollis, magna elit varius ante, in consectetur felis est commodo turpis. Proin nec pharetra elit. Vestibulum felis turpis, luctus non congue quis, pharetra nec metus. Vivamus a odio nunc. Quisque eget faucibus lorem, eget lobortis erat. Praesent ac justo elit. Pellentesque ut gravida arcu. Mauris vehicula diam nec neque fringilla, non convallis enim dictum. Nullam nec mattis ligula, nec vehicula erat. Phasellus dolor orci, ullamcorper mattis dapibus nec, sagittis quis ligula. Pellentesque ut consectetur ligula, sed ultricies risus. Fusce lacus turpis, viverra vitae diam id, ullamcorper mollis velit. Nunc eu pharetra risus. Nulla non mauris non enim ultrices dictum ut quis quam.\n\n\nMauris sed efficitur velit. Vestibulum blandit euismod lectus, quis elementum ligula elementum sed. Donec interdum a mauris vel efficitur. Morbi pretium erat eget ligula rhoncus rhoncus. Proin condimentum ante sed mauris tincidunt lobortis. Vivamus sollicitudin metus nibh, eu bibendum odio semper et. Ut egestas pulvinar sem at maximus. Integer in diam sit amet risus aliquam condimentum eu quis urna.\n\n\nEtiam dictum, elit id facilisis vulputate, neque mauris ultricies quam, nec consectetur elit lectus at nibh. Vestibulum neque turpis, sodales a erat vel, suscipit sodales lacus. Mauris gravida leo enim, et ornare metus facilisis eget. Nulla sit amet turpis molestie, sodales eros non, dapibus tortor. Etiam leo tellus, suscipit eu leo at, auctor pellentesque nisi. Nunc rhoncus scelerisque turpis eu facilisis. Nam ut metus vel urna sodales tempor. Sed vel ligula lectus. Proin sollicitudin consequat nibh, vitae ultrices tellus sollicitudin a. Pellentesque fermentum ex ac odio aliquam, ac ornare enim vulputate. Sed nunc dolor, consequat vel aliquam a, sollicitudin quis nunc. Pellentesque mi dolor, tristique congue odio vel, lobortis ornare arcu. Donec quis varius lorem.\n\n\nEtiam nisi odio, rutrum at laoreet et, cursus nec dolor. Maecenas vulputate accumsan erat. Quisque sit amet mauris ac risus cursus vestibulum a vitae mauris. Cras imperdiet, est at imperdiet auctor, augue eros rutrum mauris, et vulputate ex lacus sit amet neque. Integer accumsan tortor consequat, ultricies nibh eget, tempor odio. Ut sit amet nulla ut quam molestie accumsan. Phasellus sodales mi eros, rutrum pretium dui interdum ac. Cras aliquam lobortis augue sed vestibulum. Donec faucibus in libero non fermentum.\n\n\nQuisque malesuada vitae turpis in tempus. Aenean dui lacus, aliquet sit amet eros ut, gravida egestas leo. Sed ac scelerisque velit. Integer condimentum mi lorem, quis fringilla erat gravida sed. In hac habitasse platea dictumst. Vestibulum justo dolor, maximus sit amet justo et, vehicula faucibus tellus. Vestibulum et tellus tortor. Pellentesque eget vestibulum risus. Mauris tincidunt neque eu pretium scelerisque. Quisque accumsan malesuada lectus id pharetra. Proin ut elementum nibh. Nunc consequat dictum congue. Cras eget pellentesque odio. Donec id sem lacus. Nunc ut malesuada sapien.',
    ingredients: [],
    method: [],
    images: [],
    date: '25/04/2023, 14:40:28',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['Blog Post'],
    createdAt: {
      $date: '2023-04-25T09:13:17.281Z',
    },
    updatedAt: {
      $date: '2023-04-25T12:40:28.646Z',
    },
    __v: 0,
  },
  {
    _id: {
      $oid: '6554cc117ba3ba91b5a62c31',
    },
    title: 'food for life',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque venenatis vitae leo et auctor. Quisque tincidunt volutpat quam, non interdum sapien hendrerit vel. Vivamus mattis, mauris quis convallis mollis, magna elit varius ante, in consectetur felis est commodo turpis. Proin nec pharetra elit. Vestibulum felis turpis, luctus non congue quis, pharetra nec metus. Vivamus a odio nunc. Quisque eget faucibus lorem, eget lobortis erat. Praesent ac justo elit. Pellentesque ut gravida arcu. Mauris vehicula diam nec neque fringilla, non convallis enim dictum. Nullam nec mattis ligula, nec vehicula erat. Phasellus dolor orci, ullamcorper mattis dapibus nec, sagittis quis ligula. Pellentesque ut consectetur ligula, sed ultricies risus. Fusce lacus turpis, viverra vitae diam id, ullamcorper mollis velit. Nunc eu pharetra risus. Nulla non mauris non enim ultrices dictum ut quis quam.\n\n\nMauris sed efficitur velit. Vestibulum blandit euismod lectus, quis elementum ligula elementum sed. Donec interdum a mauris vel efficitur. Morbi pretium erat eget ligula rhoncus rhoncus. Proin condimentum ante sed mauris tincidunt lobortis. Vivamus sollicitudin metus nibh, eu bibendum odio semper et. Ut egestas pulvinar sem at maximus. Integer in diam sit amet risus aliquam condimentum eu quis urna.\n\n\nEtiam dictum, elit id facilisis vulputate, neque mauris ultricies quam, nec consectetur elit lectus at nibh. Vestibulum neque turpis, sodales a erat vel, suscipit sodales lacus. Mauris gravida leo enim, et ornare metus facilisis eget. Nulla sit amet turpis molestie, sodales eros non, dapibus tortor. Etiam leo tellus, suscipit eu leo at, auctor pellentesque nisi. Nunc rhoncus scelerisque turpis eu facilisis. Nam ut metus vel urna sodales tempor. Sed vel ligula lectus. Proin sollicitudin consequat nibh, vitae ultrices tellus sollicitudin a. Pellentesque fermentum ex ac odio aliquam, ac ornare enim vulputate. Sed nunc dolor, consequat vel aliquam a, sollicitudin quis nunc. Pellentesque mi dolor, tristique congue odio vel, lobortis ornare arcu. Donec quis varius lorem.\n\n\nEtiam nisi odio, rutrum at laoreet et, cursus nec dolor. Maecenas vulputate accumsan erat. Quisque sit amet mauris ac risus cursus vestibulum a vitae mauris. Cras imperdiet, est at imperdiet auctor, augue eros rutrum mauris, et vulputate ex lacus sit amet neque. Integer accumsan tortor consequat, ultricies nibh eget, tempor odio. Ut sit amet nulla ut quam molestie accumsan. Phasellus sodales mi eros, rutrum pretium dui interdum ac. Cras aliquam lobortis augue sed vestibulum. Donec faucibus in libero non fermentum.\n\n\nQuisque malesuada vitae turpis in tempus. Aenean dui lacus, aliquet sit amet eros ut, gravida egestas leo. Sed ac scelerisque velit. Integer condimentum mi lorem, quis fringilla erat gravida sed. In hac habitasse platea dictumst. Vestibulum justo dolor, maximus sit amet justo et, vehicula faucibus tellus. Vestibulum et tellus tortor. Pellentesque eget vestibulum risus. Mauris tincidunt neque eu pretium scelerisque. Quisque accumsan malesuada lectus id pharetra. Proin ut elementum nibh. Nunc consequat dictum congue. Cras eget pellentesque odio. Donec id sem lacus. Nunc ut malesuada sapien.',
    ingredients: [],
    method: [],
    images: [],
    date: '25/04/2023, 14:40:28',
    author: {
      $oid: '64fb2bb32fc8149bf0d4b25a',
    },
    tags: ['Blog Post'],
    createdAt: {
      $date: '2023-04-25T09:13:17.281Z',
    },
    updatedAt: {
      $date: '2023-04-25T12:40:28.646Z',
    },
    __v: 0,
  },
];
