import Head from 'next/head'
import Card from '../../components/Card'
import { useEffect, useState } from 'react'

export default function Home() {
  const [posts, setPosts] = useState([])


  useEffect(() => {
    const getAllPosts = async () => {
      const response = await fetch('/api')
      const allPosts = await response.json()
      setPosts(allPosts)
    }

    getAllPosts()
  }, [])

  console.log(posts)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>posts</h1>
      <ul>
        {posts.map(post => {
          if (post.featured) {
            return <li key={post._id}>{post.title}</li>
          }
        })}
      </ul>
    </>
  )
}
