import Head from 'next/head'
import Card from '../../components/Card'
import { useEffect, useState } from 'react'

const MONGODB_URI = process.env.MONGODB_URI;
export default function Home() {
  const [posts, setPosts] = useState([])


  console.log('-----------------------MONGODB', MONGODB_URI)


  useEffect(() => {
    const getAllPosts = async () => {
      const response = await fetch('/api')
      const allPosts = await response.json()
      setPosts(allPosts)
    }
    getAllPosts()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>posts</h1>
      <ul>
        {posts.map(post => {
          if (post.featured) {
            return <Card key={post._id} title={post.title} image={post.images[0]} tags={post.tags} />
          }
        })}
      </ul>
    </>
  )
}
